repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    - id: isort

  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black

  - repo: https://github.com/csachs/pyproject-flake8
    rev: v6.0.0
    hooks:
    - id: pyproject-flake8

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    - id: pydocstyle
      additional_dependencies: ['toml']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    - id: mypy
