name: Python package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
         auto-update-conda: true
         activate-environment: anaconda-client-env
         python-version: 3.8
         auto-activate-base: false
    - name: Version info
      shell: bash -l {0}
      run: |
        set -xe
        conda info
        python --version
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        set -xe
        which python
        pip --version
        pip install wheel
        pip install -r requirements-dev.txt
        pip install -e .
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        set -xe
        pip install pytest
        python -m pytest -v
